
title: Kate's homepage
description: This is a portfolio of my digital humanities projects from the Fall 2024 semester!
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
